/**
 * Seed script for licensing_requirements table — ALL Aceable Insurance PL states.
 * Run: npx tsx scripts/seed-licensing-requirements.ts
 *
 * Data sources:
 *   - Aceable product pages (insurance.aceable.com/pre-license/[state])
 *   - State DOI websites
 *   - Pearson VUE / PSI / Prometric exam catalogs
 *
 * Prices shown are MSRP (non-sale) from Aceable product pages.
 */
import { config } from 'dotenv';
config({ path: '.env.local' });

import { Pool, neonConfig } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-serverless';
import ws from 'ws';
import { licensingRequirements, type NewLicensingRequirement } from '../src/db/schema';

neonConfig.webSocketConstructor = ws;
const pool = new Pool({ connectionString: process.env['DATABASE_URL']! });
const db = drizzle({ client: pool });

// =========================================================================
// Helper — shared field defaults
// =========================================================================
const defaults = {
  examRequired: true,
  examPassingScore: 70,
  backgroundCheckRequired: false,
  backgroundCheckFee: null,
  fingerprintRequired: false,
  minimumAge: 18,
  residencyRequired: false,
  reciprocityAvailable: true,
  examRetakeWaitDays: 0,
  comingSoon: false,
} satisfies Partial<NewLicensingRequirement>;

// =========================================================================
// ALL STATES
// =========================================================================
const allRequirements: NewLicensingRequirement[] = [

  // =====================================================================
  // ARIZONA
  // =====================================================================
  {
    ...defaults,
    state: 'AZ',
    stateName: 'Arizona',
    lineOfAuthority: 'life-health',
    lineOfAuthorityLabel: 'Life & Health',
    totalPreLicenseHours: 0,
    courseTopics: 'Life insurance, Health insurance, Annuities, Arizona insurance law, Ethics',
    examProvider: 'Pearson VUE',
    examFee: '44.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '10.00',
    reciprocityNotes: 'Arizona offers reciprocity with most states for non-resident applicants.',
    estimatedTimelineDays: 21,
    doiUrl: 'https://insurance.az.gov/licensees-and-agents',
    examProviderUrl: 'https://home.pearsonvue.com/az/insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/arizona/',
    aceableProductPrice: '239.00',
    notes: 'Arizona does not mandate pre-license education hours, but passing the state exam is required. Aceable offers exam prep courses. Exam has general and state sections — must score 70% on each independently.',
  },
  {
    ...defaults,
    state: 'AZ',
    stateName: 'Arizona',
    lineOfAuthority: 'property-casualty',
    lineOfAuthorityLabel: 'Property & Casualty',
    totalPreLicenseHours: 0,
    courseTopics: 'Property insurance, Casualty insurance, Auto insurance, Homeowners, Arizona insurance law, Ethics',
    examProvider: 'Pearson VUE',
    examFee: '44.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '10.00',
    reciprocityNotes: 'Arizona offers reciprocity with most states for non-resident applicants.',
    estimatedTimelineDays: 21,
    doiUrl: 'https://insurance.az.gov/licensees-and-agents',
    examProviderUrl: 'https://home.pearsonvue.com/az/insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/arizona/',
    aceableProductPrice: '239.00',
    notes: 'Arizona does not mandate pre-license education hours. Exam has general and state sections — must score 70% on each independently.',
  },

  // =====================================================================
  // CALIFORNIA (Coming Soon)
  // =====================================================================
  {
    ...defaults,
    state: 'CA',
    stateName: 'California',
    lineOfAuthority: 'life-health',
    lineOfAuthorityLabel: 'Life & Health',
    totalPreLicenseHours: 20,
    courseTopics: 'Life insurance, Health insurance, Annuities, California insurance law, Ethics',
    examProvider: 'PSI',
    examFee: '88.00',
    examQuestions: 150,
    examTimeMinutes: 180,
    stateLicenseFee: '55.00',
    backgroundCheckRequired: true,
    backgroundCheckFee: '49.00',
    fingerprintRequired: true,
    reciprocityNotes: 'California does not participate in NAIC reciprocity agreements. Non-resident applicants must hold an active home-state license.',
    estimatedTimelineDays: 30,
    doiUrl: 'https://www.insurance.ca.gov/0200-industry/0010-producer-licensing/',
    examProviderUrl: 'https://test-takers.psiexams.com/cadi',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/california/',
    aceableProductPrice: null,
    comingSoon: true,
    notes: 'Course coming soon. California requires 20 hours per individual line (40 for dual L&H). Fingerprints via Live Scan.',
  },
  {
    ...defaults,
    state: 'CA',
    stateName: 'California',
    lineOfAuthority: 'property-casualty',
    lineOfAuthorityLabel: 'Property & Casualty',
    totalPreLicenseHours: 20,
    courseTopics: 'Property insurance, Casualty insurance, Auto, Homeowners, California insurance law, Ethics',
    examProvider: 'PSI',
    examFee: '88.00',
    examQuestions: 150,
    examTimeMinutes: 180,
    stateLicenseFee: '55.00',
    backgroundCheckRequired: true,
    backgroundCheckFee: '49.00',
    fingerprintRequired: true,
    reciprocityNotes: 'California does not participate in NAIC reciprocity agreements.',
    estimatedTimelineDays: 30,
    doiUrl: 'https://www.insurance.ca.gov/0200-industry/0010-producer-licensing/',
    examProviderUrl: 'https://test-takers.psiexams.com/cadi',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/california/',
    aceableProductPrice: null,
    comingSoon: true,
    notes: 'Course coming soon. California requires 20 hours per individual line. Fingerprints via Live Scan.',
  },

  // =====================================================================
  // FLORIDA
  // =====================================================================
  {
    ...defaults,
    state: 'FL',
    stateName: 'Florida',
    lineOfAuthority: 'life-health',
    lineOfAuthorityLabel: 'Life & Health',
    totalPreLicenseHours: 60,
    courseTopics: 'Life insurance, Health insurance, Medicare, Annuities, Long-term care, Florida insurance law, Ethics',
    examProvider: 'Pearson VUE',
    examFee: '45.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '55.00',
    backgroundCheckRequired: true,
    backgroundCheckFee: '43.25',
    fingerprintRequired: true,
    reciprocityNotes: 'Florida offers reciprocity with most states. Non-resident applicants with active home-state license can apply without FL pre-license education.',
    estimatedTimelineDays: 30,
    doiUrl: 'https://myfloridacfo.com/division/agents/licensure/general',
    examProviderUrl: 'https://home.pearsonvue.com/fl/insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/florida/',
    aceableProductPrice: '249.00',
    notes: 'Florida administers L&H and General Lines exams separately. 60 hours required for L&H. Fingerprints via IdentoGO.',
  },
  {
    ...defaults,
    state: 'FL',
    stateName: 'Florida',
    lineOfAuthority: 'property-casualty',
    lineOfAuthorityLabel: 'Property & Casualty (General Lines)',
    totalPreLicenseHours: 200,
    courseTopics: 'Property insurance, Casualty insurance, Auto, Homeowners, Liability, Commercial property, Florida insurance law, Ethics',
    examProvider: 'Pearson VUE',
    examFee: '45.00',
    examQuestions: 200,
    examTimeMinutes: 210,
    stateLicenseFee: '55.00',
    backgroundCheckRequired: true,
    backgroundCheckFee: '43.25',
    fingerprintRequired: true,
    reciprocityNotes: 'Florida offers reciprocity with most states.',
    estimatedTimelineDays: 60,
    doiUrl: 'https://myfloridacfo.com/division/agents/licensure/general',
    examProviderUrl: 'https://home.pearsonvue.com/fl/insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/florida/',
    aceableProductPrice: '299.00',
    notes: 'Florida General Lines (P&C) requires 200 hours of pre-license education — the highest in the nation. Plan for 6-8 weeks of study.',
  },
  {
    ...defaults,
    state: 'FL',
    stateName: 'Florida',
    lineOfAuthority: 'personal-lines',
    lineOfAuthorityLabel: 'Personal Lines',
    totalPreLicenseHours: 60,
    courseTopics: 'Personal auto, Homeowners, Renters, Personal umbrella, Florida insurance law, Ethics',
    examProvider: 'Pearson VUE',
    examFee: '45.00',
    examQuestions: 100,
    examTimeMinutes: 120,
    stateLicenseFee: '55.00',
    backgroundCheckRequired: true,
    backgroundCheckFee: '43.25',
    fingerprintRequired: true,
    reciprocityNotes: 'Florida offers reciprocity with most states.',
    estimatedTimelineDays: 30,
    doiUrl: 'https://myfloridacfo.com/division/agents/licensure/general',
    examProviderUrl: 'https://home.pearsonvue.com/fl/insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/florida/',
    aceableProductPrice: '249.00',
    notes: 'Personal Lines is a limited license restricted to personal (non-commercial) property and casualty insurance.',
  },

  // =====================================================================
  // GEORGIA
  // =====================================================================
  {
    ...defaults,
    state: 'GA',
    stateName: 'Georgia',
    lineOfAuthority: 'life-health',
    lineOfAuthorityLabel: 'Life & Health',
    totalPreLicenseHours: 16,
    courseTopics: 'Life insurance, Annuities, Health insurance, Disability insurance, Georgia insurance law, Ethics',
    examProvider: 'Pearson VUE',
    examFee: '42.00',
    examQuestions: 135,
    examTimeMinutes: 150,
    stateLicenseFee: '15.00',
    reciprocityNotes: 'Georgia offers reciprocity with most states.',
    estimatedTimelineDays: 14,
    doiUrl: 'https://oci.georgia.gov/licensing',
    examProviderUrl: 'https://home.pearsonvue.com/ga/insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/georgia/',
    aceableProductPrice: '279.00',
    notes: 'Georgia requires only 16 hours of pre-license education per line. Exam is 75% national content and 25% Georgia-specific. Must score 70% on each section independently.',
  },
  {
    ...defaults,
    state: 'GA',
    stateName: 'Georgia',
    lineOfAuthority: 'property-casualty',
    lineOfAuthorityLabel: 'Property & Casualty',
    totalPreLicenseHours: 16,
    courseTopics: 'Property insurance, Casualty insurance, Auto, Homeowners, Liability, Georgia insurance law, Ethics',
    examProvider: 'Pearson VUE',
    examFee: '42.00',
    examQuestions: 135,
    examTimeMinutes: 150,
    stateLicenseFee: '15.00',
    reciprocityNotes: 'Georgia offers reciprocity with most states.',
    estimatedTimelineDays: 14,
    doiUrl: 'https://oci.georgia.gov/licensing',
    examProviderUrl: 'https://home.pearsonvue.com/ga/insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/georgia/',
    aceableProductPrice: '279.00',
    notes: 'Georgia requires only 16 hours per line. Exam is 75% national / 25% state-specific.',
  },

  // =====================================================================
  // ILLINOIS
  // =====================================================================
  {
    ...defaults,
    state: 'IL',
    stateName: 'Illinois',
    lineOfAuthority: 'life-health',
    lineOfAuthorityLabel: 'Life & Health',
    totalPreLicenseHours: 40,
    courseTopics: 'Life insurance, Accident & Health insurance, Annuities, Illinois insurance law, Ethics',
    examProvider: 'Pearson VUE',
    examFee: '58.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '30.00',
    reciprocityNotes: 'Illinois offers reciprocity with most states.',
    estimatedTimelineDays: 28,
    doiUrl: 'https://insurance.illinois.gov/Licensure/producerlicensing.html',
    examProviderUrl: 'https://home.pearsonvue.com/il/insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/illinois/',
    aceableProductPrice: '310.00',
    notes: 'Illinois requires 20 hours per individual line (Life, A&H, Property, Casualty). L&H combined = 40 hours. Two forms of valid government-issued ID required for exam (one with photo).',
  },
  {
    ...defaults,
    state: 'IL',
    stateName: 'Illinois',
    lineOfAuthority: 'property-casualty',
    lineOfAuthorityLabel: 'Property & Casualty',
    totalPreLicenseHours: 40,
    courseTopics: 'Property insurance, Casualty insurance, Auto, Homeowners, Commercial, Illinois insurance law, Ethics',
    examProvider: 'Pearson VUE',
    examFee: '58.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '30.00',
    reciprocityNotes: 'Illinois offers reciprocity with most states.',
    estimatedTimelineDays: 28,
    doiUrl: 'https://insurance.illinois.gov/Licensure/producerlicensing.html',
    examProviderUrl: 'https://home.pearsonvue.com/il/insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/illinois/',
    aceableProductPrice: '310.00',
    notes: 'Illinois requires 20 hours per individual line. P&C combined = 40 hours.',
  },

  // =====================================================================
  // LOUISIANA (Coming Soon)
  // =====================================================================
  {
    ...defaults,
    state: 'LA',
    stateName: 'Louisiana',
    lineOfAuthority: 'life-health',
    lineOfAuthorityLabel: 'Life & Health',
    totalPreLicenseHours: 0,
    courseTopics: 'Life insurance, Health insurance, Annuities, Louisiana insurance law, Ethics',
    examProvider: 'PSI',
    examFee: '42.00',
    examPassingScore: 70,
    examQuestions: null,
    examTimeMinutes: null,
    stateLicenseFee: '50.00',
    backgroundCheckRequired: true,
    fingerprintRequired: true,
    reciprocityNotes: 'Louisiana offers reciprocity with most states.',
    estimatedTimelineDays: 21,
    doiUrl: 'https://www.ldi.la.gov/licensing-702',
    examProviderUrl: 'https://candidate.psiexams.com',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/louisiana/',
    aceableProductPrice: null,
    comingSoon: true,
    notes: 'Course coming soon. Louisiana does not mandate pre-licensing education to sit for the exam. Fingerprinting through IdentoGO. CE: 24 hours every 2 years including 3 hours ethics.',
  },
  {
    ...defaults,
    state: 'LA',
    stateName: 'Louisiana',
    lineOfAuthority: 'property-casualty',
    lineOfAuthorityLabel: 'Property & Casualty',
    totalPreLicenseHours: 0,
    courseTopics: 'Property insurance, Casualty insurance, Auto, Homeowners, Louisiana insurance law, Ethics',
    examProvider: 'PSI',
    examFee: '42.00',
    examPassingScore: 70,
    examQuestions: null,
    examTimeMinutes: null,
    stateLicenseFee: '50.00',
    backgroundCheckRequired: true,
    fingerprintRequired: true,
    reciprocityNotes: 'Louisiana offers reciprocity with most states.',
    estimatedTimelineDays: 21,
    doiUrl: 'https://www.ldi.la.gov/licensing-702',
    examProviderUrl: 'https://candidate.psiexams.com',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/louisiana/',
    aceableProductPrice: null,
    comingSoon: true,
    notes: 'Course coming soon. Louisiana does not mandate pre-licensing education. P&C agents need additional flood insurance training for CE.',
  },

  // =====================================================================
  // MASSACHUSETTS
  // =====================================================================
  {
    ...defaults,
    state: 'MA',
    stateName: 'Massachusetts',
    lineOfAuthority: 'life-health',
    lineOfAuthorityLabel: 'Life & Health',
    totalPreLicenseHours: 0,
    courseTopics: 'Life insurance, Health insurance, Annuities, Massachusetts insurance law, Ethics',
    examProvider: 'Prometric',
    examFee: '54.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '30.00',
    reciprocityNotes: 'Massachusetts offers reciprocity with most states.',
    estimatedTimelineDays: 21,
    doiUrl: 'https://www.mass.gov/insurance-licensing',
    examProviderUrl: 'https://www.prometric.com/massachusetts-insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/massachusetts/',
    aceableProductPrice: '279.00',
    notes: 'Massachusetts does not require pre-license education. Aceable offers exam prep. Exam is ~70% national content and ~30% state-specific.',
  },
  {
    ...defaults,
    state: 'MA',
    stateName: 'Massachusetts',
    lineOfAuthority: 'property-casualty',
    lineOfAuthorityLabel: 'Property & Casualty',
    totalPreLicenseHours: 0,
    courseTopics: 'Property insurance, Casualty insurance, Auto, Homeowners, Massachusetts insurance law, Ethics',
    examProvider: 'Prometric',
    examFee: '54.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '30.00',
    reciprocityNotes: 'Massachusetts offers reciprocity with most states.',
    estimatedTimelineDays: 21,
    doiUrl: 'https://www.mass.gov/insurance-licensing',
    examProviderUrl: 'https://www.prometric.com/massachusetts-insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/massachusetts/',
    aceableProductPrice: '279.00',
    notes: 'Massachusetts does not require pre-license education. Aceable offers exam prep.',
  },

  // =====================================================================
  // MICHIGAN (Coming Soon)
  // =====================================================================
  {
    ...defaults,
    state: 'MI',
    stateName: 'Michigan',
    lineOfAuthority: 'life-health',
    lineOfAuthorityLabel: 'Life & Health',
    totalPreLicenseHours: 40,
    courseTopics: 'Life insurance, Health insurance, Annuities, Michigan insurance law, Ethics',
    examProvider: 'Prometric',
    examFee: '42.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '10.00',
    reciprocityNotes: 'Michigan offers reciprocity with most states.',
    estimatedTimelineDays: 28,
    doiUrl: 'https://www.michigan.gov/difs/consumers/insurance/agent',
    examProviderUrl: 'https://www.prometric.com/michigan-insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/michigan/',
    aceableProductPrice: null,
    comingSoon: true,
    notes: 'Course coming soon. Michigan requires 40 hours of pre-license education.',
  },
  {
    ...defaults,
    state: 'MI',
    stateName: 'Michigan',
    lineOfAuthority: 'property-casualty',
    lineOfAuthorityLabel: 'Property & Casualty',
    totalPreLicenseHours: 40,
    courseTopics: 'Property insurance, Casualty insurance, Auto, Homeowners, Michigan insurance law, Ethics',
    examProvider: 'Prometric',
    examFee: '42.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '10.00',
    reciprocityNotes: 'Michigan offers reciprocity with most states.',
    estimatedTimelineDays: 28,
    doiUrl: 'https://www.michigan.gov/difs/consumers/insurance/agent',
    examProviderUrl: 'https://www.prometric.com/michigan-insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/michigan/',
    aceableProductPrice: null,
    comingSoon: true,
    notes: 'Course coming soon. Michigan requires 40 hours of pre-license education.',
  },

  // =====================================================================
  // MISSOURI
  // =====================================================================
  {
    ...defaults,
    state: 'MO',
    stateName: 'Missouri',
    lineOfAuthority: 'life-health',
    lineOfAuthorityLabel: 'Life & Health',
    totalPreLicenseHours: 0,
    courseTopics: 'Life insurance, Health insurance, Annuities, Missouri insurance law, Ethics',
    examProvider: 'Pearson VUE',
    examFee: '42.00',
    examQuestions: 100,
    examTimeMinutes: 150,
    stateLicenseFee: '100.00',
    reciprocityNotes: 'Missouri offers reciprocity with most states.',
    estimatedTimelineDays: 21,
    doiUrl: 'https://insurance.mo.gov/agents/',
    examProviderUrl: 'https://home.pearsonvue.com/mo/insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/missouri/',
    aceableProductPrice: '249.00',
    notes: 'Missouri does not require pre-licensing education. Exam: 100 questions, 2-3 hours. Must pass both national and state sections with 70%.',
  },
  {
    ...defaults,
    state: 'MO',
    stateName: 'Missouri',
    lineOfAuthority: 'property-casualty',
    lineOfAuthorityLabel: 'Property & Casualty',
    totalPreLicenseHours: 0,
    courseTopics: 'Property insurance, Casualty insurance, Auto, Homeowners, Commercial, Missouri insurance law, Ethics',
    examProvider: 'Pearson VUE',
    examFee: '42.00',
    examQuestions: 170,
    examTimeMinutes: 180,
    stateLicenseFee: '100.00',
    reciprocityNotes: 'Missouri offers reciprocity with most states.',
    estimatedTimelineDays: 21,
    doiUrl: 'https://insurance.mo.gov/agents/',
    examProviderUrl: 'https://home.pearsonvue.com/mo/insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/missouri/',
    aceableProductPrice: '249.00',
    notes: 'Missouri does not require pre-licensing education. P&C exam: 170 questions, 3 hours.',
  },

  // =====================================================================
  // NEW YORK (Coming Soon)
  // =====================================================================
  {
    ...defaults,
    state: 'NY',
    stateName: 'New York',
    lineOfAuthority: 'life-health',
    lineOfAuthorityLabel: 'Life & Health',
    totalPreLicenseHours: 40,
    courseTopics: 'Life insurance, Accident & Health insurance, Annuities, New York insurance law, Ethics',
    examProvider: 'PSI',
    examFee: '50.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '40.00',
    reciprocityNotes: 'New York offers reciprocity with most states.',
    estimatedTimelineDays: 30,
    doiUrl: 'https://www.dfs.ny.gov/industry/insurance_agents_brokers',
    examProviderUrl: 'https://candidate.psiexams.com',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/new-york/',
    aceableProductPrice: null,
    comingSoon: true,
    notes: 'Course coming soon. New York requires 40 hours for combined L&H (20 each for Life and A&H individually).',
  },
  {
    ...defaults,
    state: 'NY',
    stateName: 'New York',
    lineOfAuthority: 'property-casualty',
    lineOfAuthorityLabel: 'Property & Casualty',
    totalPreLicenseHours: 90,
    courseTopics: 'Property insurance, Casualty insurance, Auto, Homeowners, Commercial, New York insurance law, Ethics',
    examProvider: 'PSI',
    examFee: '50.00',
    examQuestions: 200,
    examTimeMinutes: 210,
    stateLicenseFee: '40.00',
    reciprocityNotes: 'New York offers reciprocity with most states.',
    estimatedTimelineDays: 45,
    doiUrl: 'https://www.dfs.ny.gov/industry/insurance_agents_brokers',
    examProviderUrl: 'https://candidate.psiexams.com',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/new-york/',
    aceableProductPrice: null,
    comingSoon: true,
    notes: 'Course coming soon. New York requires 90 hours for P&C — one of the highest requirements nationally.',
  },

  // =====================================================================
  // NORTH CAROLINA (Coming Soon)
  // =====================================================================
  {
    ...defaults,
    state: 'NC',
    stateName: 'North Carolina',
    lineOfAuthority: 'life-health',
    lineOfAuthorityLabel: 'Life & Health',
    totalPreLicenseHours: 0,
    courseTopics: 'Life insurance, Health insurance, Annuities, North Carolina insurance law, Ethics',
    examProvider: 'Pearson VUE',
    examFee: '42.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '25.00',
    reciprocityNotes: 'North Carolina offers reciprocity with most states.',
    estimatedTimelineDays: 21,
    doiUrl: 'https://www.ncdoi.gov/insurance-industry/licensing-and-education',
    examProviderUrl: 'https://home.pearsonvue.com/nc/insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/north-carolina/',
    aceableProductPrice: null,
    comingSoon: true,
    notes: 'Course coming soon. North Carolina eliminated mandatory pre-licensing education as of October 1, 2025. Passing the state exam is still required.',
  },
  {
    ...defaults,
    state: 'NC',
    stateName: 'North Carolina',
    lineOfAuthority: 'property-casualty',
    lineOfAuthorityLabel: 'Property & Casualty',
    totalPreLicenseHours: 0,
    courseTopics: 'Property insurance, Casualty insurance, Auto, Homeowners, North Carolina insurance law, Ethics',
    examProvider: 'Pearson VUE',
    examFee: '42.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '25.00',
    reciprocityNotes: 'North Carolina offers reciprocity with most states.',
    estimatedTimelineDays: 21,
    doiUrl: 'https://www.ncdoi.gov/insurance-industry/licensing-and-education',
    examProviderUrl: 'https://home.pearsonvue.com/nc/insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/north-carolina/',
    aceableProductPrice: null,
    comingSoon: true,
    notes: 'Course coming soon. North Carolina eliminated mandatory pre-licensing education as of October 1, 2025.',
  },

  // =====================================================================
  // OHIO
  // =====================================================================
  {
    ...defaults,
    state: 'OH',
    stateName: 'Ohio',
    lineOfAuthority: 'life-health',
    lineOfAuthorityLabel: 'Life & Health',
    totalPreLicenseHours: 40,
    courseTopics: 'Life insurance, Health insurance, Annuities, Ohio insurance law, Ethics',
    examProvider: 'PSI',
    examFee: '42.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '25.00',
    reciprocityNotes: 'Ohio offers reciprocity with most states.',
    estimatedTimelineDays: 28,
    doiUrl: 'https://insurance.ohio.gov/licensing-and-education',
    examProviderUrl: 'https://candidate.psiexams.com',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/ohio/',
    aceableProductPrice: '279.00',
    notes: 'Ohio requires 20 hours per individual line (Life, Health, Property, Casualty). Combined L&H = 40 hours.',
  },
  {
    ...defaults,
    state: 'OH',
    stateName: 'Ohio',
    lineOfAuthority: 'property-casualty',
    lineOfAuthorityLabel: 'Property & Casualty',
    totalPreLicenseHours: 40,
    courseTopics: 'Property insurance, Casualty insurance, Auto, Homeowners, Commercial, Ohio insurance law, Ethics',
    examProvider: 'PSI',
    examFee: '42.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '25.00',
    reciprocityNotes: 'Ohio offers reciprocity with most states.',
    estimatedTimelineDays: 28,
    doiUrl: 'https://insurance.ohio.gov/licensing-and-education',
    examProviderUrl: 'https://candidate.psiexams.com',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/ohio/',
    aceableProductPrice: '279.00',
    notes: 'Ohio requires 20 hours per individual line. Combined P&C = 40 hours.',
  },

  // =====================================================================
  // OKLAHOMA (Coming Soon)
  // =====================================================================
  {
    ...defaults,
    state: 'OK',
    stateName: 'Oklahoma',
    lineOfAuthority: 'life-health',
    lineOfAuthorityLabel: 'Life & Health',
    totalPreLicenseHours: 0,
    courseTopics: 'Life insurance, Health insurance, Annuities, Oklahoma insurance law, Ethics',
    examProvider: 'PSI',
    examFee: '42.00',
    examQuestions: null,
    examTimeMinutes: null,
    stateLicenseFee: '25.00',
    reciprocityNotes: 'Oklahoma offers reciprocity with most states.',
    estimatedTimelineDays: 21,
    doiUrl: 'https://www.oid.ok.gov/licensing/',
    examProviderUrl: 'https://candidate.psiexams.com',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/oklahoma/',
    aceableProductPrice: null,
    comingSoon: true,
    notes: 'Course coming soon. Oklahoma does not require pre-licensing education to sit for the state exam.',
  },
  {
    ...defaults,
    state: 'OK',
    stateName: 'Oklahoma',
    lineOfAuthority: 'property-casualty',
    lineOfAuthorityLabel: 'Property & Casualty',
    totalPreLicenseHours: 0,
    courseTopics: 'Property insurance, Casualty insurance, Auto, Homeowners, Oklahoma insurance law, Ethics',
    examProvider: 'PSI',
    examFee: '42.00',
    examQuestions: null,
    examTimeMinutes: null,
    stateLicenseFee: '25.00',
    reciprocityNotes: 'Oklahoma offers reciprocity with most states.',
    estimatedTimelineDays: 21,
    doiUrl: 'https://www.oid.ok.gov/licensing/',
    examProviderUrl: 'https://candidate.psiexams.com',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/oklahoma/',
    aceableProductPrice: null,
    comingSoon: true,
    notes: 'Course coming soon. Oklahoma does not require pre-licensing education.',
  },

  // =====================================================================
  // PENNSYLVANIA
  // =====================================================================
  {
    ...defaults,
    state: 'PA',
    stateName: 'Pennsylvania',
    lineOfAuthority: 'life-health',
    lineOfAuthorityLabel: 'Life & Health',
    totalPreLicenseHours: 24,
    courseTopics: 'Life insurance, Health insurance, Annuities, Pennsylvania insurance law, Ethics',
    examProvider: 'PSI',
    examFee: '43.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '55.00',
    reciprocityNotes: 'Pennsylvania offers reciprocity with most states.',
    estimatedTimelineDays: 21,
    doiUrl: 'https://www.insurance.pa.gov/Licensees/Pages/default.aspx',
    examProviderUrl: 'https://candidate.psiexams.com',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/pennsylvania/',
    aceableProductPrice: '260.00',
    notes: 'Pennsylvania is one of the fastest paths to licensure — typically 3-4 weeks from start to license. PSI offers both remote proctored and in-person testing.',
  },
  {
    ...defaults,
    state: 'PA',
    stateName: 'Pennsylvania',
    lineOfAuthority: 'property-casualty',
    lineOfAuthorityLabel: 'Property & Casualty',
    totalPreLicenseHours: 24,
    courseTopics: 'Property insurance, Casualty insurance, Auto, Homeowners, Commercial, Pennsylvania insurance law, Ethics',
    examProvider: 'PSI',
    examFee: '43.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '55.00',
    reciprocityNotes: 'Pennsylvania offers reciprocity with most states.',
    estimatedTimelineDays: 21,
    doiUrl: 'https://www.insurance.pa.gov/Licensees/Pages/default.aspx',
    examProviderUrl: 'https://candidate.psiexams.com',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/pennsylvania/',
    aceableProductPrice: '260.00',
    notes: 'Pennsylvania is one of the fastest paths to licensure — typically 3-4 weeks.',
  },

  // =====================================================================
  // SOUTH CAROLINA (Coming Soon)
  // =====================================================================
  {
    ...defaults,
    state: 'SC',
    stateName: 'South Carolina',
    lineOfAuthority: 'life-health',
    lineOfAuthorityLabel: 'Life & Health',
    totalPreLicenseHours: 0,
    courseTopics: 'Life insurance, Health insurance, Annuities, South Carolina insurance law, Ethics',
    examProvider: 'Pearson VUE',
    examFee: '42.00',
    examQuestions: null,
    examTimeMinutes: null,
    stateLicenseFee: '25.00',
    reciprocityNotes: 'South Carolina offers reciprocity with most states.',
    estimatedTimelineDays: 21,
    doiUrl: 'https://doi.sc.gov/licensing',
    examProviderUrl: 'https://home.pearsonvue.com/sc/insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/south-carolina/',
    aceableProductPrice: null,
    comingSoon: true,
    notes: 'Course coming soon. South Carolina does not require pre-licensing education to take the state exam.',
  },
  {
    ...defaults,
    state: 'SC',
    stateName: 'South Carolina',
    lineOfAuthority: 'property-casualty',
    lineOfAuthorityLabel: 'Property & Casualty',
    totalPreLicenseHours: 0,
    courseTopics: 'Property insurance, Casualty insurance, Auto, Homeowners, South Carolina insurance law, Ethics',
    examProvider: 'Pearson VUE',
    examFee: '42.00',
    examQuestions: null,
    examTimeMinutes: null,
    stateLicenseFee: '25.00',
    reciprocityNotes: 'South Carolina offers reciprocity with most states.',
    estimatedTimelineDays: 21,
    doiUrl: 'https://doi.sc.gov/licensing',
    examProviderUrl: 'https://home.pearsonvue.com/sc/insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/south-carolina/',
    aceableProductPrice: null,
    comingSoon: true,
    notes: 'Course coming soon. South Carolina does not require pre-licensing education.',
  },

  // =====================================================================
  // TENNESSEE
  // =====================================================================
  {
    ...defaults,
    state: 'TN',
    stateName: 'Tennessee',
    lineOfAuthority: 'life-health',
    lineOfAuthorityLabel: 'Life & Health',
    totalPreLicenseHours: 20,
    courseTopics: 'Life insurance, Health insurance, Annuities, Tennessee insurance law, Ethics',
    examProvider: 'Pearson VUE',
    examFee: '42.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '50.00',
    backgroundCheckRequired: true,
    fingerprintRequired: true,
    reciprocityNotes: 'Tennessee offers reciprocity with most states.',
    estimatedTimelineDays: 28,
    doiUrl: 'https://www.tn.gov/commerce/insurance/licensing.html',
    examProviderUrl: 'https://home.pearsonvue.com/tn/insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/tennessee/',
    aceableProductPrice: '249.00',
    notes: 'Exam scheduling available within 24 hours. Fingerprinting same-day or next-day via IdentoGO. Application processing typically 10-15 business days through NIPR.',
  },
  {
    ...defaults,
    state: 'TN',
    stateName: 'Tennessee',
    lineOfAuthority: 'property-casualty',
    lineOfAuthorityLabel: 'Property & Casualty',
    totalPreLicenseHours: 20,
    courseTopics: 'Property insurance, Casualty insurance, Auto, Homeowners, Commercial, Tennessee insurance law, Ethics',
    examProvider: 'Pearson VUE',
    examFee: '42.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '50.00',
    backgroundCheckRequired: true,
    fingerprintRequired: true,
    reciprocityNotes: 'Tennessee offers reciprocity with most states.',
    estimatedTimelineDays: 28,
    doiUrl: 'https://www.tn.gov/commerce/insurance/licensing.html',
    examProviderUrl: 'https://home.pearsonvue.com/tn/insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/tennessee/',
    aceableProductPrice: '249.00',
    notes: 'Exam scheduling available within 24 hours. Fingerprinting via IdentoGO.',
  },

  // =====================================================================
  // TEXAS
  // =====================================================================
  {
    ...defaults,
    state: 'TX',
    stateName: 'Texas',
    lineOfAuthority: 'property-casualty',
    lineOfAuthorityLabel: 'Property & Casualty',
    totalPreLicenseHours: 40,
    courseTopics: 'Property insurance, Casualty insurance, Texas insurance law, Ethics, General insurance concepts',
    examProvider: 'Pearson VUE',
    examFee: '62.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '50.00',
    backgroundCheckRequired: true,
    backgroundCheckFee: '38.25',
    fingerprintRequired: true,
    reciprocityNotes: 'Texas offers reciprocity with most states. Non-resident applicants with an active home-state license may apply without completing TX pre-license education.',
    estimatedTimelineDays: 21,
    doiUrl: 'https://www.tdi.texas.gov/agent/become-an-agent.html',
    examProviderUrl: 'https://home.pearsonvue.com/tx/insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/texas/',
    aceableProductPrice: '259.00',
    notes: 'Texas requires a separate exam for each line of authority. P&C covers both property and casualty in one exam. Fingerprints submitted electronically via IdentoGO.',
  },
  {
    ...defaults,
    state: 'TX',
    stateName: 'Texas',
    lineOfAuthority: 'life-health',
    lineOfAuthorityLabel: 'Life & Health',
    totalPreLicenseHours: 40,
    courseTopics: 'Life insurance, Health insurance, Annuities, Texas insurance law, Ethics, Policy provisions',
    examProvider: 'Pearson VUE',
    examFee: '62.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '50.00',
    backgroundCheckRequired: true,
    backgroundCheckFee: '38.25',
    fingerprintRequired: true,
    reciprocityNotes: 'Texas offers reciprocity with most states. Non-resident applicants with an active home-state license may apply without completing TX pre-license education.',
    estimatedTimelineDays: 21,
    doiUrl: 'https://www.tdi.texas.gov/agent/become-an-agent.html',
    examProviderUrl: 'https://home.pearsonvue.com/tx/insurance',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/texas/',
    aceableProductPrice: '259.00',
    notes: 'Texas requires a separate exam for each line of authority. L&H covers both life and health in one exam. Fingerprints submitted electronically via IdentoGO.',
  },

  // =====================================================================
  // WASHINGTON
  // =====================================================================
  {
    ...defaults,
    state: 'WA',
    stateName: 'Washington',
    lineOfAuthority: 'life-health',
    lineOfAuthorityLabel: 'Life & Health',
    totalPreLicenseHours: 20,
    courseTopics: 'Life insurance, Health insurance, Annuities, Disability, Washington insurance law, Ethics',
    examProvider: 'PSI',
    examFee: '50.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '55.00',
    reciprocityNotes: 'Washington offers reciprocity with most states.',
    estimatedTimelineDays: 21,
    doiUrl: 'https://www.insurance.wa.gov/licensing-and-education',
    examProviderUrl: 'https://candidate.psiexams.com',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/washington/',
    aceableProductPrice: '199.00',
    notes: 'Exam covers national content (70-75%) and Washington-specific content (25-30%). Results appear on screen immediately.',
  },
  {
    ...defaults,
    state: 'WA',
    stateName: 'Washington',
    lineOfAuthority: 'property-casualty',
    lineOfAuthorityLabel: 'Property & Casualty',
    totalPreLicenseHours: 20,
    courseTopics: 'Property insurance, Casualty insurance, Auto, Homeowners, Commercial, Washington insurance law, Ethics',
    examProvider: 'PSI',
    examFee: '50.00',
    examQuestions: 150,
    examTimeMinutes: 165,
    stateLicenseFee: '55.00',
    reciprocityNotes: 'Washington offers reciprocity with most states.',
    estimatedTimelineDays: 21,
    doiUrl: 'https://www.insurance.wa.gov/licensing-and-education',
    examProviderUrl: 'https://candidate.psiexams.com',
    aceableProductUrl: 'https://insurance.aceable.com/pre-license/washington/',
    aceableProductPrice: '199.00',
    notes: 'Exam covers national content (70-75%) and Washington-specific content (25-30%). Results appear on screen immediately.',
  },
];

// =========================================================================
// Run
// =========================================================================
async function seed() {
  console.log(`Seeding ${allRequirements.length} licensing requirement rows across ${new Set(allRequirements.map(r => r.state)).size} states...`);

  // Clear all existing rows and re-insert
  await db.delete(licensingRequirements);

  const inserted = await db.insert(licensingRequirements).values(allRequirements).returning();
  console.log(`Inserted ${inserted.length} rows.`);

  // Summary
  const states = [...new Set(inserted.map(r => r.stateName))].sort();
  const liveStates = [...new Set(inserted.filter(r => !r.comingSoon).map(r => r.stateName))].sort();
  const comingSoonStates = [...new Set(inserted.filter(r => r.comingSoon).map(r => r.stateName))].sort();

  console.log(`\nLive states (${liveStates.length}): ${liveStates.join(', ')}`);
  console.log(`Coming soon (${comingSoonStates.length}): ${comingSoonStates.join(', ')}`);
  console.log(`Total states: ${states.length}`);

  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
